version: '3.8'

services:
    app:
        image: node:18-alpine
        working_dir: /app
        ports:
            - 5173:5173
        volumes:
            - ./:/app
        command: sh -c "[ ! -d "node_modules" ] && yarn install; yarn dev --host 0.0.0.0"
